### DISCUSSION TITLE
How to pass --insecure-tls command line option to rectic from npbackup

### DISCUSSION THREAD

**Discussion by agb2008** [netinvent/npbackup#116] [Q&A]
I use **rest-server**, to improve security it was setup to use tls self-signed certificate to add HTTPS connection ability. If I use command line option and pure **restic** binary - I could connect to my **rest-server** repository. But from within **npbackup** I can't find a way to pass command line option "--insecure-tls" to **restic**. Is there a way to do so? I've tested on both platforms: Linux and Windows but with no luck. As far as I know there is no environment variable that could be set for **restic** that could overwrite default value for this option (--insecure-tls = false).

**Comment by deajan** [comment]
Depending on if you're using the CLI or the GUI, you can configure whatever parameters you want to pass to the restic backend in as additional_parameters.

When using a config file with CLI:
```
conf_version: 3.0
audience: public
repos:
  default:
    backup_opts:
      additional_parameters: <what you want as string>
```

In GUI, see Repo config > Environment variables > Additional parameters
![{9D843A35-095C-4E1C-BF48-13AC01634F2D}](https://github.com/user-attachments/assets/e7cd3fde-f075-4b99-b8a7-0dde7a06c84a)
