### ISSUE TITLE
Grafana Dashboard not showing values

### ISSUE THREAD

**Issue by deajan** [netinvent/npbackup#153]
@Guitarbilly: Follow-up from #132 

I guess you don't use tenants on your prometheus setup.
Mind reconfiguring the "backup_job" variable to remove tenant label filter ?

![Image](https://github.com/user-attachments/assets/7444cf3e-9da8-4830-a242-a0fc14d9e472)

**Comment by GuitarBilly** [comment]
@deajan i am very sure that when I added this dashboard it worked fine. Since I do not watch it every time, i cannot say exactly when or with what change/version/experiment it blanked out to N/A with the warning as shown in #132 . 

Can you elaborate a bit more on "tenant"?

I have done the requested change, removed the tenant filter from the backup_job and now it shows data again:
![Image](https://github.com/user-attachments/assets/26727c09-6d24-4f59-a668-59153cedbf4e)

**Comment by deajan** [comment]
So basically you can have grafana and metric storage in mono-tenant (no __tenant__ label) or multi-tenant configuration.
I've added indeed a filter to backup_job variable so only backup jobs from selected tenant are shown.
Obviously, your setup isn't multi tenant, so there's something wrong with the filter.

This being quite difficult to debug between various Grafana setups, I'd definitly need access to a mono-tenant setup so I can tune the dashboard to work on both.

**Comment by GuitarBilly** [comment]
You could easily spin up a setup via docker, I have done that for restic-server + prometheus + node_exporter + pushgateway + grafana. 

Follow steps here https://github.com/restic/rest-server/tree/master/examples/compose-with-grafana, and expand it with node_exporter and pushgateway sections, i.e.:

```
  node_exporter:
    image: prom/node-exporter:latest
    #container_name: node_exporter
    ports:
      - 9100:9100
    volumes:
      - ./node_exporter:/node_exporter
    depends_on:
      - prometheus
    command:
      - '--collector.textfile.directory=/node_exporter'
    networks:
      - net

  pushgateway:
    image: prom/pushgateway:latest
    #container_name: pushgateway
    ports:
      - "9091:9091"
    volumes:
      - ./pushgateway:/pushgateway
    depends_on:
      - prometheus
    command:
      - '--persistence.file=/pushgateway/persistence.file'
    networks:
      - net
```
